image: debian:stable

before_script:
    - apt-get update
    - apt-get install -y make sudo
    - make build-depends
    - /usr/sbin/invoke-rc.d --force redis-server start

debian:
    stage: test
    script:
        - make test

raspbian:
    stage: test
    script:
        - ./test-raspbian-chroot
