sudo: enabled
dist: bionic

language: minimal

install:
  - sudo apt-get update
  - sudo apt-get install -y make
  - sysctl net.ipv6.conf.all.disable_ipv6=0
  - sudo make build-depends
  - sudo /usr/sbin/invoke-rc.d --force redis-server start

script:
  - make test
