sudo: enabled
dist: bionic

language: minimal

install:
  - apt-get update
  - apt-get install -y make sudo
  - make build-depends
  - /usr/sbin/invoke-rc.d --force redis-server start

script:
  - make test
