---
#
# Steps to install hackman on your raspberry pi
#
# Follow the steps in the README.md
#

- name: Install hackman
  hosts: localhost

  tasks:
    - name: Tweak gpu_mem
      become: yes
      lineinfile:
        path: /boot/config.txt
        regexp: '^gpu_mem='
        line: gpu_mem=16
        insertbefore: BOF

# TODO:
# - reboot after changing the config.txt ?

    - name: Install packages
      become: yes
      apt:
          name: "{{ item }}"
          state: present
      loop:
          - make
          - nginx
          - python3-rpi.gpio
          - python3-serial

    - name: Use makefile to install required packages
      become: yes
      command: make build-depends

    - name: Run internal test suite
      command: make test

    - name: Make destination directory
      become: yes
      file:
          dest: /var/www/hackman
          state: directory
          mode: "u=rwx,a=rx"

    - name: Create user
      become: yes
      user:
          name: hackman
          home: /var/www/hackman
          generate_ssh_key: yes
          ssh_key_type: ed25519

    - name: Make db directory
      become: yes
      file:
          dest: /var/www/hackman/db
          state: directory
          user: hackman
          mode: "u=rwx,a=rx"

    - name: Install app files
      become: yes
      copy:
          src: "{{ item }}"
          dest: "/var/www/hackman/"
      loop:
          - hackman
          - hackman_door
          - hackman_notifier
          - hackman_payments
          - hackman_rfid
          - manage.py

# TODO:
# - Add hackman_notifier to the installed files? (needs fixing first)
# - only install needed files..
# - notify restart for the services on change

# TODO:
# - create database if not exists
#   - /var/www/hackman/db/db.sqlite3
#   - python3 manage.py migrate
#   - chown hackman /var/www/hackman/db/db.sqlite3*

    - name: nginx remove default site
      become: yes
      file:
          path: /etc/nginx/sites-enabled/default
          state: absent

    - name: nginx sites-available
      become: yes
      copy:
          src: nginx/default
          dest: /etc/nginx/sites-available/hackman

    - name: nginx sites-enabled
      become: yes
      file:
          src: /etc/nginx/sites-available/hackman
          dest: /etc/nginx/sites-enabled/hackman
          state: link

# TODO:
# - notify restart nginx after each nginx change

    - name: Install environment
      become: yes
      copy:
          dest: /etc/hackman.env
          mode: "a=r"
          content: |
              DJANGO_SETTINGS_MODULE=hackman.settings_prod

# TODO:
# - this should contain some other settings
#   EMAIL_HOST, EMAIL_PORT, EMAIL_HOST_USER, EMAIL_HOST_PASSWORD, RAVEN_DSN
#   but some of them are now unused and some should not be in the git repo
# - at the least, should not overwrite an existing file

    - name: hackman services
      become: yes
      copy:
          src: systemd/{{ item }}
          dest: /etc/systemd/system/{{ item }}
      loop:
          - hackman-doord.service
          - hackman-paymentimport.service
          - hackman-paymentimport.timer
          - hackman-rfidd.service
          - hackman.service

# TODO:
# hackman-backup.service hackman-backup.timer
# hackman-paymentimport.service hackman-paymentimport.timer
# hackman-paymentreminder.service hackman-paymentreminder.timer
#
# TODO:
# - reload systemd to install these services

# TODO:
# - empty database or restored database
#
