---
#
# Steps to install hackman on your raspberry pi
#
# Follow the steps in the README.md
#
# This is supposed to be a local install script to rigorously define the
# minimal steps required to make a working system.  Thus it is attempted
# to be written in a clear and simple fashion.
#
# One of the results of this is that it is not written to be dropped in
# as an ansible role in a larger system.

- name: Install hackman
  hosts: localhost

  tasks:
    - name: Tweak gpu_mem
      become: yes
      lineinfile:
        path: /boot/config.txt
        regexp: '^gpu_mem='
        line: gpu_mem=16
        insertbefore: BOF

# TODO:
# - only if running on a raspberry pi
# - reboot after changing the config.txt ?

    - name: Install packages
      become: yes
      apt:
          name: "{{ item }}"
          state: present
      loop:
          - make
          - nginx
          - python3-rpi.gpio
          - python3-serial
          - python3-mote

# TODO:
# - python3-mote only exists in the raspbian repositories

    - name: Use makefile to install required packages
      become: yes
      command: make build-depends

    - name: Run internal test suite
      command: make test

    - name: Make destination directory
      become: yes
      file:
          dest: /var/www/hackman
          state: directory
          mode: "u=rwx,a=rx"

    - name: Create user
      become: yes
      user:
          name: hackman
          home: /var/www/hackman
          generate_ssh_key: yes
          ssh_key_type: ed25519

    - name: Make db directory
      become: yes
      file:
          dest: /var/www/hackman/db
          state: directory
          owner: hackman
          mode: "u=rwx,a=rx"

    - name: Install app files
      become: yes
      synchronize:
          src: "{{ item }}"
          dest: "/var/www/hackman/"
      loop:
          - hackman
          - hackman_door
          - hackman_notifier
          - hackman_payments
          - hackman_rfid
          - manage.py

    - name: Install helper scripts
      become: yes
      copy:
          src: "{{ item }}"
          dest: "/usr/local/bin"
          mode: "a=rx"
      loop:
          - dsl-log
          - dsl-occupied
          - dsl-lights

# TODO:
# - only install needed files..
# - notify restart for the services on change

# TODO:
# - create database if not exists
#   - /var/www/hackman/db/db.sqlite3
#   - python3 manage.py migrate
#   - chown hackman /var/www/hackman/db/db.sqlite3*

    - name: nginx remove default site
      become: yes
      file:
          path: /etc/nginx/sites-enabled/default
          state: absent

    - name: nginx sites-available
      become: yes
      copy:
          src: nginx/default
          dest: /etc/nginx/sites-available/hackman

    - name: nginx sites-enabled
      become: yes
      file:
          src: /etc/nginx/sites-available/hackman
          dest: /etc/nginx/sites-enabled/hackman
          state: link

# TODO:
# - notify restart nginx after each nginx change

    - name: Install environment
      become: yes
      copy:
          dest: /etc/hackman.env
          mode: "a=r"
          content: |
              DJANGO_SETTINGS_MODULE=hackman.settings_prod

# TODO:
# - this should contain some other settings
#   EMAIL_HOST, EMAIL_PORT, EMAIL_HOST_USER, EMAIL_HOST_PASSWORD, RAVEN_DSN
#   but some of them are now unused and some should not be in the git repo
# - at the least, should not overwrite an existing file

    - name: hackman services
      become: yes
      copy:
          src: systemd/{{ item }}
          dest: /etc/systemd/system/{{ item }}
      loop:
          - hackman-doord.service
          - hackman-paymentimport.service
          - hackman-paymentimport.timer
          - hackman-rfidd.service
          - hackman.service
          - dsl-log.service
          - dsl-occupied.service
          - dsl-lights.service

# TODO:
# hackman-backup.service hackman-backup.timer
# hackman-paymentimport.service hackman-paymentimport.timer
# hackman-paymentreminder.service hackman-paymentreminder.timer
#
# TODO:
# - reload systemd to install these services

    - name: Load new service files
      become: yes
      systemd:
          daemon_reload: yes

    - name: Enable services
      become: yes
      systemd:
          name: "{{ item }}"
          enabled: yes
          state: started
      loop:
        - hackman-paymentimport.timer
        - hackman
        - hackman-rfidd
        - hackman-doord
        - dsl-log
        - dsl-occupied
        - dsl-lights

