name: deb

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install FPM
        run: sudo gem install fpm

      - name: Install FPM dependencies
        run: sudo apt-get -y install squashfs-tools

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Build deb
        run: |
          # Install Poetry
          curl -sSL https://install.python-poetry.org | python3 -

          # We want to write to _actual_ /opt as some installation processes
          # are creating hard coded shebangs pointing to the venv location.
          mkdir -p /opt

          # Create virtualenv
          python3 -m venv /opt/hackman
          . /opt/hackman/bin/activate

          # Install dependencies
          poetry install --no-interaction --no-root --no-dev

          # Install self into env
          poetry build -f wheel -n
          pip install --no-deps dist/*.whl
          rm -rf dist *.egg-info

          # Generate Django static files
          env DJANGO_SETTINGS_MODULE=hackman.settings_prod hackman-manage collectstatic

          # Create a temporary rootfs directory
          mkdir -p rootfs/opt
          mv /opt/hackman rootfs/opt/hackman

          # Create symlinks to all binaries starting with hackman* or dsl* in /usr/local/bin
          mkdir -p rootfs/usr/local/bin
          for bin in rootfs/opt/hackman/bin/dsl* rootfs/opt/hackman/bin/hackman*; do
            ln -s /opt/hackman/bin/$(basename $bin) rootfs/usr/local/bin/$(basename $bin)
          done

          # Copy systemd units
          mkdir -p rootfs/lib/systemd
          cp -rv systemd rootfs/lib/systemd/system

          # Build deb
          version=$(grep '^version' pyproject.toml | cut -d = -f 2 | jq -r)
          fpm -s dir -t deb -C rootfs --name hackman --version $version --iteration 1 --description "DSL Hackman" --depends redis-server .
